version: "2.00" # Increment only when tagging release, download link uses it.
title: Qahiri
title_ar: قاهري
description: A manuscript Kufic typeface
description_ar: خط كوفي مصحفي
logo: assets/images/favicon.svg
theme: jekyll-theme-minimal
